server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dance
    username: root
    password: admin

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
